using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;

namespace PointOfSale
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            PointOfSale.Models.subContext dbContext = new PointOfSale.Models.subContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TrInvoiceHeaders.Where(x=>x.InvoiceHeaderId == Guid.Parse("e14eecee-4bf3-4cd8-a8bc-cd2eedaeae19")).LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    trInvoiceHeadersBindingSource.DataSource = dbContext.TrInvoiceHeaders.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
