
namespace PointOfSale
{
    partial class FormCurrAcc
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormCurrAcc));
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.simpleButton1 = new DevExpress.XtraEditors.SimpleButton();
            this.btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            this.btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            this.CurrAccCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.dcCurrAccsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataLanguageCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.CurrAccTypeCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.FirstNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.LastNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.FatherNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.NewPasswordTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.ConfirmPasswordTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.IdentityNumTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.TaxNumTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.CreditLimitTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.IsVipCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            this.CustomerTypeCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.VendorTypeCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.CustomerPosDiscountRateTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.IsDisabledCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            this.RowGuidTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.BonusCardNumTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.AddressTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.PhoneNumTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.BirthDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            this.DcCurrAccTypeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.TrInvoiceHeadersGridControl = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.TrCurrAccRoleGridControl = new DevExpress.XtraGrid.GridControl();
            this.gridView2 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.CreatedUserNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.CreatedDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            this.LastUpdatedUserNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.LastUpdatedDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            this.Root = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.ItemForCurrAccCode = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup3 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.ItemForCreditLimit = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForIsVip = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForBonusCardNum = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForDataLanguageCode = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForIsDisabled = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.ItemForAddress = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForFirstName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForLastName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForFatherName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForPhoneNum = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForBirthDate = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForIdentityNum = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForTaxNum = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForCurrAccTypeCode = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForNewPassword = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForConfirmPassword = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.CurrAccCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dcCurrAccsBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataLanguageCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CurrAccTypeCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.FirstNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.FatherNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.NewPasswordTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ConfirmPasswordTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.IdentityNumTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxNumTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreditLimitTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsVipCheckEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerTypeCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.VendorTypeCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerPosDiscountRateTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsDisabledCheckEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RowGuidTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BonusCardNumTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AddressTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PhoneNumTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DcCurrAccTypeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TrInvoiceHeadersGridControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TrCurrAccRoleGridControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedUserNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedDateDateEdit.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedDateDateEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedUserNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedDateDateEdit.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedDateDateEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCurrAccCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCreditLimit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIsVip)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBonusCardNum)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForDataLanguageCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIsDisabled)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFirstName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForLastName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFatherName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPhoneNum)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBirthDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIdentityNum)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForTaxNum)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCurrAccTypeCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForNewPassword)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForConfirmPassword)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.Controls.Add(this.simpleButton1);
            this.dataLayoutControl1.Controls.Add(this.btn_Cancel);
            this.dataLayoutControl1.Controls.Add(this.btn_Ok);
            this.dataLayoutControl1.Controls.Add(this.CurrAccCodeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.DataLanguageCodeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.CurrAccTypeCodeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.FirstNameTextEdit);
            this.dataLayoutControl1.Controls.Add(this.LastNameTextEdit);
            this.dataLayoutControl1.Controls.Add(this.FatherNameTextEdit);
            this.dataLayoutControl1.Controls.Add(this.NewPasswordTextEdit);
            this.dataLayoutControl1.Controls.Add(this.ConfirmPasswordTextEdit);
            this.dataLayoutControl1.Controls.Add(this.IdentityNumTextEdit);
            this.dataLayoutControl1.Controls.Add(this.TaxNumTextEdit);
            this.dataLayoutControl1.Controls.Add(this.CreditLimitTextEdit);
            this.dataLayoutControl1.Controls.Add(this.IsVipCheckEdit);
            this.dataLayoutControl1.Controls.Add(this.CustomerTypeCodeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.VendorTypeCodeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.CustomerPosDiscountRateTextEdit);
            this.dataLayoutControl1.Controls.Add(this.IsDisabledCheckEdit);
            this.dataLayoutControl1.Controls.Add(this.RowGuidTextEdit);
            this.dataLayoutControl1.Controls.Add(this.BonusCardNumTextEdit);
            this.dataLayoutControl1.Controls.Add(this.AddressTextEdit);
            this.dataLayoutControl1.Controls.Add(this.PhoneNumTextEdit);
            this.dataLayoutControl1.Controls.Add(this.BirthDateDateEdit);
            this.dataLayoutControl1.Controls.Add(this.DcCurrAccTypeTextEdit);
            this.dataLayoutControl1.Controls.Add(this.TrInvoiceHeadersGridControl);
            this.dataLayoutControl1.Controls.Add(this.TrCurrAccRoleGridControl);
            this.dataLayoutControl1.Controls.Add(this.CreatedUserNameTextEdit);
            this.dataLayoutControl1.Controls.Add(this.CreatedDateDateEdit);
            this.dataLayoutControl1.Controls.Add(this.LastUpdatedUserNameTextEdit);
            this.dataLayoutControl1.Controls.Add(this.LastUpdatedDateDateEdit);
            this.dataLayoutControl1.DataSource = this.dcCurrAccsBindingSource;
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(1023, 140, 650, 400);
            this.dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            this.dataLayoutControl1.Root = this.Root;
            this.dataLayoutControl1.Size = new System.Drawing.Size(770, 401);
            this.dataLayoutControl1.TabIndex = 0;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            this.dataLayoutControl1.FieldRetrieving += new System.EventHandler<DevExpress.XtraDataLayout.FieldRetrievingEventArgs>(this.dataLayoutControl1_FieldRetrieving);
            // 
            // simpleButton1
            // 
            this.simpleButton1.Location = new System.Drawing.Point(528, 318);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new System.Drawing.Size(74, 71);
            this.simpleButton1.StyleController = this.dataLayoutControl1;
            this.simpleButton1.TabIndex = 8;
            this.simpleButton1.Text = "simpleButton1";
            this.simpleButton1.Click += new System.EventHandler(this.simpleButton1_Click);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            this.btn_Cancel.ImageOptions.SvgImage = ((DevExpress.Utils.Svg.SvgImage)(resources.GetObject("btn_Cancel.ImageOptions.SvgImage")));
            this.btn_Cancel.Location = new System.Drawing.Point(606, 318);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(74, 71);
            this.btn_Cancel.StyleController = this.dataLayoutControl1;
            this.btn_Cancel.TabIndex = 5;
            this.btn_Cancel.Text = "simpleButton2";
            // 
            // btn_Ok
            // 
            this.btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            this.btn_Ok.ImageOptions.SvgImage = ((DevExpress.Utils.Svg.SvgImage)(resources.GetObject("btn_Ok.ImageOptions.SvgImage")));
            this.btn_Ok.Location = new System.Drawing.Point(684, 318);
            this.btn_Ok.Name = "btn_Ok";
            this.btn_Ok.Size = new System.Drawing.Size(74, 71);
            this.btn_Ok.StyleController = this.dataLayoutControl1;
            this.btn_Ok.TabIndex = 4;
            this.btn_Ok.Text = "simpleButton1";
            this.btn_Ok.Click += new System.EventHandler(this.btn_Ok_Click);
            // 
            // CurrAccCodeTextEdit
            // 
            this.CurrAccCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CurrAccCode", true));
            this.CurrAccCodeTextEdit.Location = new System.Drawing.Point(125, 12);
            this.CurrAccCodeTextEdit.Name = "CurrAccCodeTextEdit";
            this.CurrAccCodeTextEdit.Size = new System.Drawing.Size(257, 20);
            this.CurrAccCodeTextEdit.StyleController = this.dataLayoutControl1;
            this.CurrAccCodeTextEdit.TabIndex = 6;
            // 
            // dcCurrAccsBindingSource
            // 
            this.dcCurrAccsBindingSource.DataSource = typeof(PointOfSale.Models.DcCurrAcc);
            this.dcCurrAccsBindingSource.AddingNew += new System.ComponentModel.AddingNewEventHandler(this.dcCurrAccsBindingSource_AddingNew);
            // 
            // DataLanguageCodeTextEdit
            // 
            this.DataLanguageCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "DataLanguageCode", true));
            this.DataLanguageCodeTextEdit.Location = new System.Drawing.Point(499, 234);
            this.DataLanguageCodeTextEdit.Name = "DataLanguageCodeTextEdit";
            this.DataLanguageCodeTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.DataLanguageCodeTextEdit.Size = new System.Drawing.Size(247, 20);
            this.DataLanguageCodeTextEdit.StyleController = this.dataLayoutControl1;
            this.DataLanguageCodeTextEdit.TabIndex = 7;
            // 
            // CurrAccTypeCodeTextEdit
            // 
            this.CurrAccTypeCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CurrAccTypeCode", true));
            this.CurrAccTypeCodeTextEdit.Location = new System.Drawing.Point(125, 36);
            this.CurrAccTypeCodeTextEdit.Name = "CurrAccTypeCodeTextEdit";
            this.CurrAccTypeCodeTextEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.CurrAccTypeCodeTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.CurrAccTypeCodeTextEdit.Properties.Mask.EditMask = "N0";
            this.CurrAccTypeCodeTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.CurrAccTypeCodeTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.CurrAccTypeCodeTextEdit.Size = new System.Drawing.Size(258, 20);
            this.CurrAccTypeCodeTextEdit.StyleController = this.dataLayoutControl1;
            this.CurrAccTypeCodeTextEdit.TabIndex = 9;
            // 
            // FirstNameTextEdit
            // 
            this.FirstNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "FirstName", true));
            this.FirstNameTextEdit.Location = new System.Drawing.Point(137, 93);
            this.FirstNameTextEdit.Name = "FirstNameTextEdit";
            this.FirstNameTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.FirstNameTextEdit.Size = new System.Drawing.Size(245, 20);
            this.FirstNameTextEdit.StyleController = this.dataLayoutControl1;
            this.FirstNameTextEdit.TabIndex = 12;
            // 
            // LastNameTextEdit
            // 
            this.LastNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "LastName", true));
            this.LastNameTextEdit.Location = new System.Drawing.Point(137, 117);
            this.LastNameTextEdit.Name = "LastNameTextEdit";
            this.LastNameTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.LastNameTextEdit.Size = new System.Drawing.Size(245, 20);
            this.LastNameTextEdit.StyleController = this.dataLayoutControl1;
            this.LastNameTextEdit.TabIndex = 13;
            // 
            // FatherNameTextEdit
            // 
            this.FatherNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "FatherName", true));
            this.FatherNameTextEdit.Location = new System.Drawing.Point(137, 141);
            this.FatherNameTextEdit.Name = "FatherNameTextEdit";
            this.FatherNameTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.FatherNameTextEdit.Size = new System.Drawing.Size(245, 20);
            this.FatherNameTextEdit.StyleController = this.dataLayoutControl1;
            this.FatherNameTextEdit.TabIndex = 14;
            // 
            // NewPasswordTextEdit
            // 
            this.NewPasswordTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "NewPassword", true));
            this.NewPasswordTextEdit.Location = new System.Drawing.Point(499, 12);
            this.NewPasswordTextEdit.Name = "NewPasswordTextEdit";
            this.NewPasswordTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.NewPasswordTextEdit.Properties.UseSystemPasswordChar = true;
            this.NewPasswordTextEdit.Size = new System.Drawing.Size(259, 20);
            this.NewPasswordTextEdit.StyleController = this.dataLayoutControl1;
            this.NewPasswordTextEdit.TabIndex = 15;
            // 
            // ConfirmPasswordTextEdit
            // 
            this.ConfirmPasswordTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "ConfirmPassword", true));
            this.ConfirmPasswordTextEdit.Location = new System.Drawing.Point(500, 36);
            this.ConfirmPasswordTextEdit.Name = "ConfirmPasswordTextEdit";
            this.ConfirmPasswordTextEdit.Properties.UseSystemPasswordChar = true;
            this.ConfirmPasswordTextEdit.Size = new System.Drawing.Size(258, 20);
            this.ConfirmPasswordTextEdit.StyleController = this.dataLayoutControl1;
            this.ConfirmPasswordTextEdit.TabIndex = 16;
            // 
            // IdentityNumTextEdit
            // 
            this.IdentityNumTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "IdentityNum", true));
            this.IdentityNumTextEdit.Location = new System.Drawing.Point(499, 117);
            this.IdentityNumTextEdit.Name = "IdentityNumTextEdit";
            this.IdentityNumTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.IdentityNumTextEdit.Size = new System.Drawing.Size(247, 20);
            this.IdentityNumTextEdit.StyleController = this.dataLayoutControl1;
            this.IdentityNumTextEdit.TabIndex = 17;
            // 
            // TaxNumTextEdit
            // 
            this.TaxNumTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "TaxNum", true));
            this.TaxNumTextEdit.Location = new System.Drawing.Point(499, 141);
            this.TaxNumTextEdit.Name = "TaxNumTextEdit";
            this.TaxNumTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            this.TaxNumTextEdit.Size = new System.Drawing.Size(247, 20);
            this.TaxNumTextEdit.StyleController = this.dataLayoutControl1;
            this.TaxNumTextEdit.TabIndex = 18;
            // 
            // CreditLimitTextEdit
            // 
            this.CreditLimitTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CreditLimit", true));
            this.CreditLimitTextEdit.Location = new System.Drawing.Point(137, 258);
            this.CreditLimitTextEdit.Name = "CreditLimitTextEdit";
            this.CreditLimitTextEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.CreditLimitTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.CreditLimitTextEdit.Properties.Mask.EditMask = "G";
            this.CreditLimitTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.CreditLimitTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.CreditLimitTextEdit.Size = new System.Drawing.Size(245, 20);
            this.CreditLimitTextEdit.StyleController = this.dataLayoutControl1;
            this.CreditLimitTextEdit.TabIndex = 19;
            // 
            // IsVipCheckEdit
            // 
            this.IsVipCheckEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "IsVip", true));
            this.IsVipCheckEdit.Location = new System.Drawing.Point(386, 258);
            this.IsVipCheckEdit.Name = "IsVipCheckEdit";
            this.IsVipCheckEdit.Properties.Caption = "VIP";
            this.IsVipCheckEdit.Properties.GlyphAlignment = DevExpress.Utils.HorzAlignment.Default;
            this.IsVipCheckEdit.Size = new System.Drawing.Size(360, 20);
            this.IsVipCheckEdit.StyleController = this.dataLayoutControl1;
            this.IsVipCheckEdit.TabIndex = 20;
            // 
            // CustomerTypeCodeTextEdit
            // 
            this.CustomerTypeCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CustomerTypeCode", true));
            this.CustomerTypeCodeTextEdit.Location = new System.Drawing.Point(140, 464);
            this.CustomerTypeCodeTextEdit.Name = "CustomerTypeCodeTextEdit";
            this.CustomerTypeCodeTextEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.CustomerTypeCodeTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.CustomerTypeCodeTextEdit.Properties.Mask.EditMask = "N0";
            this.CustomerTypeCodeTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.CustomerTypeCodeTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.CustomerTypeCodeTextEdit.Size = new System.Drawing.Size(601, 20);
            this.CustomerTypeCodeTextEdit.StyleController = this.dataLayoutControl1;
            this.CustomerTypeCodeTextEdit.TabIndex = 21;
            // 
            // VendorTypeCodeTextEdit
            // 
            this.VendorTypeCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "VendorTypeCode", true));
            this.VendorTypeCodeTextEdit.Location = new System.Drawing.Point(140, 488);
            this.VendorTypeCodeTextEdit.Name = "VendorTypeCodeTextEdit";
            this.VendorTypeCodeTextEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.VendorTypeCodeTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.VendorTypeCodeTextEdit.Properties.Mask.EditMask = "N0";
            this.VendorTypeCodeTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.VendorTypeCodeTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.VendorTypeCodeTextEdit.Size = new System.Drawing.Size(601, 20);
            this.VendorTypeCodeTextEdit.StyleController = this.dataLayoutControl1;
            this.VendorTypeCodeTextEdit.TabIndex = 22;
            // 
            // CustomerPosDiscountRateTextEdit
            // 
            this.CustomerPosDiscountRateTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CustomerPosDiscountRate", true));
            this.CustomerPosDiscountRateTextEdit.Location = new System.Drawing.Point(140, 512);
            this.CustomerPosDiscountRateTextEdit.Name = "CustomerPosDiscountRateTextEdit";
            this.CustomerPosDiscountRateTextEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.CustomerPosDiscountRateTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.CustomerPosDiscountRateTextEdit.Properties.Mask.EditMask = "F";
            this.CustomerPosDiscountRateTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.CustomerPosDiscountRateTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.CustomerPosDiscountRateTextEdit.Size = new System.Drawing.Size(601, 20);
            this.CustomerPosDiscountRateTextEdit.StyleController = this.dataLayoutControl1;
            this.CustomerPosDiscountRateTextEdit.TabIndex = 23;
            // 
            // IsDisabledCheckEdit
            // 
            this.IsDisabledCheckEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "IsDisabled", true));
            this.IsDisabledCheckEdit.Location = new System.Drawing.Point(12, 294);
            this.IsDisabledCheckEdit.Name = "IsDisabledCheckEdit";
            this.IsDisabledCheckEdit.Properties.Caption = "Qeyri-Aktiv";
            this.IsDisabledCheckEdit.Properties.GlyphAlignment = DevExpress.Utils.HorzAlignment.Default;
            this.IsDisabledCheckEdit.Size = new System.Drawing.Size(746, 20);
            this.IsDisabledCheckEdit.StyleController = this.dataLayoutControl1;
            this.IsDisabledCheckEdit.TabIndex = 24;
            // 
            // RowGuidTextEdit
            // 
            this.RowGuidTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "RowGuid", true));
            this.RowGuidTextEdit.Location = new System.Drawing.Point(140, 560);
            this.RowGuidTextEdit.Name = "RowGuidTextEdit";
            this.RowGuidTextEdit.Size = new System.Drawing.Size(601, 20);
            this.RowGuidTextEdit.StyleController = this.dataLayoutControl1;
            this.RowGuidTextEdit.TabIndex = 25;
            // 
            // BonusCardNumTextEdit
            // 
            this.BonusCardNumTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "BonusCardNum", true));
            this.BonusCardNumTextEdit.Location = new System.Drawing.Point(137, 234);
            this.BonusCardNumTextEdit.Name = "BonusCardNumTextEdit";
            this.BonusCardNumTextEdit.Size = new System.Drawing.Size(245, 20);
            this.BonusCardNumTextEdit.StyleController = this.dataLayoutControl1;
            this.BonusCardNumTextEdit.TabIndex = 26;
            // 
            // AddressTextEdit
            // 
            this.AddressTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "Address", true));
            this.AddressTextEdit.Location = new System.Drawing.Point(499, 165);
            this.AddressTextEdit.Name = "AddressTextEdit";
            this.AddressTextEdit.Size = new System.Drawing.Size(247, 20);
            this.AddressTextEdit.StyleController = this.dataLayoutControl1;
            this.AddressTextEdit.TabIndex = 27;
            // 
            // PhoneNumTextEdit
            // 
            this.PhoneNumTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "PhoneNum", true));
            this.PhoneNumTextEdit.Location = new System.Drawing.Point(137, 165);
            this.PhoneNumTextEdit.Name = "PhoneNumTextEdit";
            this.PhoneNumTextEdit.Properties.Mask.EditMask = "(999) 000-0000";
            this.PhoneNumTextEdit.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Simple;
            this.PhoneNumTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.PhoneNumTextEdit.Size = new System.Drawing.Size(245, 20);
            this.PhoneNumTextEdit.StyleController = this.dataLayoutControl1;
            this.PhoneNumTextEdit.TabIndex = 28;
            // 
            // BirthDateDateEdit
            // 
            this.BirthDateDateEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "BirthDate", true));
            this.BirthDateDateEdit.EditValue = null;
            this.BirthDateDateEdit.Location = new System.Drawing.Point(499, 93);
            this.BirthDateDateEdit.Name = "BirthDateDateEdit";
            this.BirthDateDateEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.BirthDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.BirthDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.BirthDateDateEdit.Size = new System.Drawing.Size(247, 20);
            this.BirthDateDateEdit.StyleController = this.dataLayoutControl1;
            this.BirthDateDateEdit.TabIndex = 29;
            // 
            // DcCurrAccTypeTextEdit
            // 
            this.DcCurrAccTypeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "DcCurrAccType", true));
            this.DcCurrAccTypeTextEdit.Location = new System.Drawing.Point(140, 680);
            this.DcCurrAccTypeTextEdit.Name = "DcCurrAccTypeTextEdit";
            this.DcCurrAccTypeTextEdit.Size = new System.Drawing.Size(601, 20);
            this.DcCurrAccTypeTextEdit.StyleController = this.dataLayoutControl1;
            this.DcCurrAccTypeTextEdit.TabIndex = 30;
            // 
            // TrInvoiceHeadersGridControl
            // 
            this.TrInvoiceHeadersGridControl.DataBindings.Add(new System.Windows.Forms.Binding("DataSource", this.dcCurrAccsBindingSource, "TrInvoiceHeaders", true));
            this.TrInvoiceHeadersGridControl.Location = new System.Drawing.Point(12, 704);
            this.TrInvoiceHeadersGridControl.MainView = this.gridView1;
            this.TrInvoiceHeadersGridControl.Name = "TrInvoiceHeadersGridControl";
            this.TrInvoiceHeadersGridControl.Size = new System.Drawing.Size(729, 20);
            this.TrInvoiceHeadersGridControl.TabIndex = 31;
            this.TrInvoiceHeadersGridControl.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.GridControl = this.TrInvoiceHeadersGridControl;
            this.gridView1.Name = "gridView1";
            // 
            // TrCurrAccRoleGridControl
            // 
            this.TrCurrAccRoleGridControl.DataBindings.Add(new System.Windows.Forms.Binding("DataSource", this.dcCurrAccsBindingSource, "TrCurrAccRole", true));
            this.TrCurrAccRoleGridControl.Location = new System.Drawing.Point(12, 728);
            this.TrCurrAccRoleGridControl.MainView = this.gridView2;
            this.TrCurrAccRoleGridControl.Name = "TrCurrAccRoleGridControl";
            this.TrCurrAccRoleGridControl.Size = new System.Drawing.Size(729, 20);
            this.TrCurrAccRoleGridControl.TabIndex = 32;
            this.TrCurrAccRoleGridControl.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView2});
            // 
            // gridView2
            // 
            this.gridView2.GridControl = this.TrCurrAccRoleGridControl;
            this.gridView2.Name = "gridView2";
            // 
            // CreatedUserNameTextEdit
            // 
            this.CreatedUserNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CreatedUserName", true));
            this.CreatedUserNameTextEdit.Location = new System.Drawing.Point(140, 752);
            this.CreatedUserNameTextEdit.Name = "CreatedUserNameTextEdit";
            this.CreatedUserNameTextEdit.Size = new System.Drawing.Size(601, 20);
            this.CreatedUserNameTextEdit.StyleController = this.dataLayoutControl1;
            this.CreatedUserNameTextEdit.TabIndex = 33;
            // 
            // CreatedDateDateEdit
            // 
            this.CreatedDateDateEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "CreatedDate", true));
            this.CreatedDateDateEdit.EditValue = null;
            this.CreatedDateDateEdit.Location = new System.Drawing.Point(140, 776);
            this.CreatedDateDateEdit.Name = "CreatedDateDateEdit";
            this.CreatedDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.CreatedDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.CreatedDateDateEdit.Size = new System.Drawing.Size(601, 20);
            this.CreatedDateDateEdit.StyleController = this.dataLayoutControl1;
            this.CreatedDateDateEdit.TabIndex = 34;
            // 
            // LastUpdatedUserNameTextEdit
            // 
            this.LastUpdatedUserNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "LastUpdatedUserName", true));
            this.LastUpdatedUserNameTextEdit.Location = new System.Drawing.Point(140, 800);
            this.LastUpdatedUserNameTextEdit.Name = "LastUpdatedUserNameTextEdit";
            this.LastUpdatedUserNameTextEdit.Size = new System.Drawing.Size(601, 20);
            this.LastUpdatedUserNameTextEdit.StyleController = this.dataLayoutControl1;
            this.LastUpdatedUserNameTextEdit.TabIndex = 35;
            // 
            // LastUpdatedDateDateEdit
            // 
            this.LastUpdatedDateDateEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dcCurrAccsBindingSource, "LastUpdatedDate", true));
            this.LastUpdatedDateDateEdit.EditValue = null;
            this.LastUpdatedDateDateEdit.Location = new System.Drawing.Point(140, 824);
            this.LastUpdatedDateDateEdit.Name = "LastUpdatedDateDateEdit";
            this.LastUpdatedDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.LastUpdatedDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.LastUpdatedDateDateEdit.Size = new System.Drawing.Size(601, 20);
            this.LastUpdatedDateDateEdit.StyleController = this.dataLayoutControl1;
            this.LastUpdatedDateDateEdit.TabIndex = 36;
            // 
            // Root
            // 
            this.Root.CustomizationFormText = "Root";
            this.Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.Root.GroupBordersVisible = false;
            this.Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.Root.Name = "Root";
            this.Root.Size = new System.Drawing.Size(770, 401);
            this.Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForCurrAccCode,
            this.layoutControlGroup3,
            this.ItemForIsDisabled,
            this.layoutControlGroup2,
            this.ItemForCurrAccTypeCode,
            this.ItemForNewPassword,
            this.ItemForConfirmPassword,
            this.layoutControlItem1,
            this.layoutControlItem2,
            this.emptySpaceItem1,
            this.layoutControlItem3});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(750, 381);
            // 
            // ItemForCurrAccCode
            // 
            this.ItemForCurrAccCode.Control = this.CurrAccCodeTextEdit;
            this.ItemForCurrAccCode.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForCurrAccCode.CustomizationFormText = "Cari Hesab Kodu";
            this.ItemForCurrAccCode.Location = new System.Drawing.Point(0, 0);
            this.ItemForCurrAccCode.Name = "ItemForCurrAccCode";
            this.ItemForCurrAccCode.Size = new System.Drawing.Size(374, 24);
            this.ItemForCurrAccCode.Text = "Cari Hesab Kodu";
            this.ItemForCurrAccCode.TextSize = new System.Drawing.Size(101, 13);
            // 
            // layoutControlGroup3
            // 
            this.layoutControlGroup3.CustomizationFormText = "layoutControlGroup3";
            this.layoutControlGroup3.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForCreditLimit,
            this.ItemForIsVip,
            this.ItemForBonusCardNum,
            this.ItemForDataLanguageCode});
            this.layoutControlGroup3.Location = new System.Drawing.Point(0, 189);
            this.layoutControlGroup3.Name = "layoutControlGroup3";
            this.layoutControlGroup3.Size = new System.Drawing.Size(750, 93);
            // 
            // ItemForCreditLimit
            // 
            this.ItemForCreditLimit.Control = this.CreditLimitTextEdit;
            this.ItemForCreditLimit.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForCreditLimit.CustomizationFormText = "Kredit Limiti";
            this.ItemForCreditLimit.Location = new System.Drawing.Point(0, 24);
            this.ItemForCreditLimit.Name = "ItemForCreditLimit";
            this.ItemForCreditLimit.Size = new System.Drawing.Size(362, 24);
            this.ItemForCreditLimit.Text = "Kredit Limiti";
            this.ItemForCreditLimit.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForIsVip
            // 
            this.ItemForIsVip.Control = this.IsVipCheckEdit;
            this.ItemForIsVip.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForIsVip.CustomizationFormText = "VIP";
            this.ItemForIsVip.Location = new System.Drawing.Point(362, 24);
            this.ItemForIsVip.Name = "ItemForIsVip";
            this.ItemForIsVip.Size = new System.Drawing.Size(364, 24);
            this.ItemForIsVip.Text = "VIP";
            this.ItemForIsVip.TextSize = new System.Drawing.Size(0, 0);
            this.ItemForIsVip.TextVisible = false;
            // 
            // ItemForBonusCardNum
            // 
            this.ItemForBonusCardNum.Control = this.BonusCardNumTextEdit;
            this.ItemForBonusCardNum.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForBonusCardNum.CustomizationFormText = "Bonus Kartı";
            this.ItemForBonusCardNum.Location = new System.Drawing.Point(0, 0);
            this.ItemForBonusCardNum.Name = "ItemForBonusCardNum";
            this.ItemForBonusCardNum.Size = new System.Drawing.Size(362, 24);
            this.ItemForBonusCardNum.Text = "Bonus Kartı";
            this.ItemForBonusCardNum.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForDataLanguageCode
            // 
            this.ItemForDataLanguageCode.Control = this.DataLanguageCodeTextEdit;
            this.ItemForDataLanguageCode.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForDataLanguageCode.CustomizationFormText = "Data Language Code";
            this.ItemForDataLanguageCode.Location = new System.Drawing.Point(362, 0);
            this.ItemForDataLanguageCode.Name = "ItemForDataLanguageCode";
            this.ItemForDataLanguageCode.Size = new System.Drawing.Size(364, 24);
            this.ItemForDataLanguageCode.Text = "Data Language Code";
            this.ItemForDataLanguageCode.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForIsDisabled
            // 
            this.ItemForIsDisabled.Control = this.IsDisabledCheckEdit;
            this.ItemForIsDisabled.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForIsDisabled.CustomizationFormText = "Qeyri-Aktiv";
            this.ItemForIsDisabled.Location = new System.Drawing.Point(0, 282);
            this.ItemForIsDisabled.Name = "ItemForIsDisabled";
            this.ItemForIsDisabled.Size = new System.Drawing.Size(750, 24);
            this.ItemForIsDisabled.Text = "Qeyri-Aktiv";
            this.ItemForIsDisabled.TextSize = new System.Drawing.Size(0, 0);
            this.ItemForIsDisabled.TextVisible = false;
            // 
            // layoutControlGroup2
            // 
            this.layoutControlGroup2.CustomizationFormText = "layoutControlGroup2";
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForAddress,
            this.ItemForFirstName,
            this.ItemForLastName,
            this.ItemForFatherName,
            this.ItemForPhoneNum,
            this.ItemForBirthDate,
            this.ItemForIdentityNum,
            this.ItemForTaxNum});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 48);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Size = new System.Drawing.Size(750, 141);
            // 
            // ItemForAddress
            // 
            this.ItemForAddress.Control = this.AddressTextEdit;
            this.ItemForAddress.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForAddress.CustomizationFormText = "Adres";
            this.ItemForAddress.Location = new System.Drawing.Point(362, 72);
            this.ItemForAddress.Name = "ItemForAddress";
            this.ItemForAddress.Size = new System.Drawing.Size(364, 24);
            this.ItemForAddress.Text = "Adres";
            this.ItemForAddress.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForFirstName
            // 
            this.ItemForFirstName.Control = this.FirstNameTextEdit;
            this.ItemForFirstName.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForFirstName.CustomizationFormText = "Adı";
            this.ItemForFirstName.Location = new System.Drawing.Point(0, 0);
            this.ItemForFirstName.Name = "ItemForFirstName";
            this.ItemForFirstName.Size = new System.Drawing.Size(362, 24);
            this.ItemForFirstName.Text = "Adı";
            this.ItemForFirstName.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForLastName
            // 
            this.ItemForLastName.Control = this.LastNameTextEdit;
            this.ItemForLastName.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForLastName.CustomizationFormText = "Soyadı";
            this.ItemForLastName.Location = new System.Drawing.Point(0, 24);
            this.ItemForLastName.Name = "ItemForLastName";
            this.ItemForLastName.Size = new System.Drawing.Size(362, 24);
            this.ItemForLastName.Text = "Soyadı";
            this.ItemForLastName.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForFatherName
            // 
            this.ItemForFatherName.Control = this.FatherNameTextEdit;
            this.ItemForFatherName.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForFatherName.CustomizationFormText = "Ata Adı";
            this.ItemForFatherName.Location = new System.Drawing.Point(0, 48);
            this.ItemForFatherName.Name = "ItemForFatherName";
            this.ItemForFatherName.Size = new System.Drawing.Size(362, 24);
            this.ItemForFatherName.Text = "Ata Adı";
            this.ItemForFatherName.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForPhoneNum
            // 
            this.ItemForPhoneNum.Control = this.PhoneNumTextEdit;
            this.ItemForPhoneNum.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForPhoneNum.CustomizationFormText = "Telefon";
            this.ItemForPhoneNum.Location = new System.Drawing.Point(0, 72);
            this.ItemForPhoneNum.Name = "ItemForPhoneNum";
            this.ItemForPhoneNum.Size = new System.Drawing.Size(362, 24);
            this.ItemForPhoneNum.Text = "Telefon";
            this.ItemForPhoneNum.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForBirthDate
            // 
            this.ItemForBirthDate.Control = this.BirthDateDateEdit;
            this.ItemForBirthDate.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForBirthDate.CustomizationFormText = "Doğum Günü";
            this.ItemForBirthDate.Location = new System.Drawing.Point(362, 0);
            this.ItemForBirthDate.Name = "ItemForBirthDate";
            this.ItemForBirthDate.Size = new System.Drawing.Size(364, 24);
            this.ItemForBirthDate.Text = "Doğum Günü";
            this.ItemForBirthDate.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForIdentityNum
            // 
            this.ItemForIdentityNum.Control = this.IdentityNumTextEdit;
            this.ItemForIdentityNum.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForIdentityNum.CustomizationFormText = "Ş.V.Nömrəsi";
            this.ItemForIdentityNum.Location = new System.Drawing.Point(362, 24);
            this.ItemForIdentityNum.Name = "ItemForIdentityNum";
            this.ItemForIdentityNum.Size = new System.Drawing.Size(364, 24);
            this.ItemForIdentityNum.Text = "Ş.V.Nömrəsi";
            this.ItemForIdentityNum.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForTaxNum
            // 
            this.ItemForTaxNum.Control = this.TaxNumTextEdit;
            this.ItemForTaxNum.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForTaxNum.CustomizationFormText = "Vergi Nömrəsi";
            this.ItemForTaxNum.Location = new System.Drawing.Point(362, 48);
            this.ItemForTaxNum.Name = "ItemForTaxNum";
            this.ItemForTaxNum.Size = new System.Drawing.Size(364, 24);
            this.ItemForTaxNum.Text = "Vergi Nömrəsi";
            this.ItemForTaxNum.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForCurrAccTypeCode
            // 
            this.ItemForCurrAccTypeCode.Control = this.CurrAccTypeCodeTextEdit;
            this.ItemForCurrAccTypeCode.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForCurrAccTypeCode.CustomizationFormText = "Cari Hesab Tipi Kodu";
            this.ItemForCurrAccTypeCode.Location = new System.Drawing.Point(0, 24);
            this.ItemForCurrAccTypeCode.Name = "ItemForCurrAccTypeCode";
            this.ItemForCurrAccTypeCode.Size = new System.Drawing.Size(375, 24);
            this.ItemForCurrAccTypeCode.Text = "Cari Hesab Tipi Kodu";
            this.ItemForCurrAccTypeCode.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForNewPassword
            // 
            this.ItemForNewPassword.Control = this.NewPasswordTextEdit;
            this.ItemForNewPassword.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForNewPassword.CustomizationFormText = "Yeni Şifrə";
            this.ItemForNewPassword.Location = new System.Drawing.Point(374, 0);
            this.ItemForNewPassword.Name = "ItemForNewPassword";
            this.ItemForNewPassword.Size = new System.Drawing.Size(376, 24);
            this.ItemForNewPassword.TextSize = new System.Drawing.Size(101, 13);
            // 
            // ItemForConfirmPassword
            // 
            this.ItemForConfirmPassword.Control = this.ConfirmPasswordTextEdit;
            this.ItemForConfirmPassword.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForConfirmPassword.CustomizationFormText = "Şifrəni Təsdiqlə";
            this.ItemForConfirmPassword.Location = new System.Drawing.Point(375, 24);
            this.ItemForConfirmPassword.Name = "ItemForConfirmPassword";
            this.ItemForConfirmPassword.Size = new System.Drawing.Size(375, 24);
            this.ItemForConfirmPassword.TextSize = new System.Drawing.Size(101, 13);
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.btn_Ok;
            this.layoutControlItem1.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.Location = new System.Drawing.Point(672, 306);
            this.layoutControlItem1.MinSize = new System.Drawing.Size(78, 26);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(78, 75);
            this.layoutControlItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.btn_Cancel;
            this.layoutControlItem2.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            this.layoutControlItem2.Location = new System.Drawing.Point(594, 306);
            this.layoutControlItem2.MinSize = new System.Drawing.Size(78, 26);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(78, 75);
            this.layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(0, 306);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(516, 75);
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.simpleButton1;
            this.layoutControlItem3.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.layoutControlItem3.CustomizationFormText = "layoutControlItem3";
            this.layoutControlItem3.Location = new System.Drawing.Point(516, 306);
            this.layoutControlItem3.MinSize = new System.Drawing.Size(78, 26);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(78, 75);
            this.layoutControlItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem3.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem3.TextVisible = false;
            // 
            // FormCurrAcc
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(770, 401);
            this.Controls.Add(this.dataLayoutControl1);
            this.Name = "FormCurrAcc";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.FormCurrAcc_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.CurrAccCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dcCurrAccsBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataLanguageCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CurrAccTypeCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.FirstNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.FatherNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.NewPasswordTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ConfirmPasswordTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.IdentityNumTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxNumTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreditLimitTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsVipCheckEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerTypeCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.VendorTypeCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerPosDiscountRateTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsDisabledCheckEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RowGuidTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BonusCardNumTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AddressTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PhoneNumTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DcCurrAccTypeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TrInvoiceHeadersGridControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TrCurrAccRoleGridControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedUserNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedDateDateEdit.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CreatedDateDateEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedUserNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedDateDateEdit.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastUpdatedDateDateEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCurrAccCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCreditLimit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIsVip)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBonusCardNum)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForDataLanguageCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIsDisabled)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFirstName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForLastName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFatherName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPhoneNum)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBirthDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForIdentityNum)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForTaxNum)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCurrAccTypeCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForNewPassword)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForConfirmPassword)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private System.Windows.Forms.BindingSource dcCurrAccsBindingSource;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;
        private DevExpress.XtraEditors.TextEdit CurrAccCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit DataLanguageCodeTextEdit;
        private DevExpress.XtraEditors.SimpleButton simpleButton1;
        private DevExpress.XtraEditors.TextEdit CurrAccTypeCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit FirstNameTextEdit;
        private DevExpress.XtraEditors.TextEdit LastNameTextEdit;
        private DevExpress.XtraEditors.TextEdit FatherNameTextEdit;
        private DevExpress.XtraEditors.TextEdit NewPasswordTextEdit;
        private DevExpress.XtraEditors.TextEdit ConfirmPasswordTextEdit;
        private DevExpress.XtraEditors.TextEdit IdentityNumTextEdit;
        private DevExpress.XtraEditors.TextEdit TaxNumTextEdit;
        private DevExpress.XtraEditors.TextEdit CreditLimitTextEdit;
        private DevExpress.XtraEditors.CheckEdit IsVipCheckEdit;
        private DevExpress.XtraEditors.TextEdit CustomerTypeCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit VendorTypeCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit CustomerPosDiscountRateTextEdit;
        private DevExpress.XtraEditors.CheckEdit IsDisabledCheckEdit;
        private DevExpress.XtraEditors.TextEdit RowGuidTextEdit;
        private DevExpress.XtraEditors.TextEdit BonusCardNumTextEdit;
        private DevExpress.XtraEditors.TextEdit AddressTextEdit;
        private DevExpress.XtraEditors.TextEdit PhoneNumTextEdit;
        private DevExpress.XtraEditors.DateEdit BirthDateDateEdit;
        private DevExpress.XtraEditors.TextEdit DcCurrAccTypeTextEdit;
        private DevExpress.XtraGrid.GridControl TrInvoiceHeadersGridControl;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private DevExpress.XtraGrid.GridControl TrCurrAccRoleGridControl;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView2;
        private DevExpress.XtraEditors.TextEdit CreatedUserNameTextEdit;
        private DevExpress.XtraEditors.DateEdit CreatedDateDateEdit;
        private DevExpress.XtraEditors.TextEdit LastUpdatedUserNameTextEdit;
        private DevExpress.XtraEditors.DateEdit LastUpdatedDateDateEdit;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccCode;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup3;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCreditLimit;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsVip;
        private DevExpress.XtraLayout.LayoutControlItem ItemForBonusCardNum;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDataLanguageCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDisabled;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup2;
        private DevExpress.XtraLayout.LayoutControlItem ItemForAddress;
        private DevExpress.XtraLayout.LayoutControlItem ItemForFirstName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLastName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForFatherName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPhoneNum;
        private DevExpress.XtraLayout.LayoutControlItem ItemForBirthDate;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIdentityNum;
        private DevExpress.XtraLayout.LayoutControlItem ItemForTaxNum;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccTypeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForNewPassword;
        private DevExpress.XtraLayout.LayoutControlItem ItemForConfirmPassword;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
    }
}